### ISSUE TITLE
Spring Boot 项目数据访问层结构不规范

### ISSUE THREAD

**Issue by cx229** [101Projects-SoftwareEngineeringPractice/HealthCode#38]
**Is your feature request related to a problem? Please describe.**
在当前的 Spring Boot 项目中，我们发现 DAO 层和 Mapper 层的设计存在不规范的地方。目前的实现中：

1. 项目没有专门的实体层（Entity Layer
2. Dao 层的代码直接包含 Entity 类。
3. Mapper 层则使用 @Mapper 注解的接口类，并通过 org.apache.ibatis.annotations 的注解实现 SQL 语句。
这种设计方式导致了代码结构不清晰，影响了项目的可维护性和扩展性。

**Describe the solution you'd like**
建议按照标准的 Spring Boot 和 MyBatis 使用规范，重构代码框架。具体方案如下：

定义实体类（Entity）层
1. 实体类应放在独立的包中，确保数据结构与数据库表一致。
```
/**
 * 实体类（POJO）
 * @author LinkinStar
 */
public class UserEntity {

    private int id;
    private String val;

    // Getters and Setters
}
```

2. 定义数据访问层（DAO）
数据访问层应独立于实体类，通过接口定义对数据库的操作方法。
```
/**
 * 数据访问层
 * @author LinkinStar
 */
public interface UserDao {

    /**
     * 查询数据
     * @return 用户列表
     */
    List<UserEntity> listUser();

    /**
     * 添加数据
     */
    boolean addUser();
}
```

3. 使用 XML 配置 SQL 语句
将 SQL 语句配置在 XML 文件中，按照 MyBatis 的标准做法进行实现。
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.dao.UserDao">

    <select id="listUser" resultType="UserEntity">
        SELECT id, val
        FROM user_tab
    </select>

    <insert id="addUser">
        INSERT INTO user_tab
        (id, val)
        VALUES (#{id}, #{val})
    </insert>
</mapper>
```

**Comment by coder-chenzhi** [comment]
LGTM
